on: [push, pull_request]
env:
  CI: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Clone repository
      uses: actions/checkout@v2.5.0

    - name: Set node.js version
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 19.x

    - name: Install npm dependencies
      run: npm install

    - name: Run tests
      run: npm run test && npm run coveralls

    - name: Coveralls
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: "Unit"

