on: [push, pull_request]
env:
  CI: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Set node.js version
      uses: actions/setup-node@v1
      with:
        node-version: 19.x

    - name: Install npm dependencies
      run: npm install

    - name: Run tests
      run: npm run test && npm run coveralls

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
